### ISSUE TITLE
What libraries did you use?

### ISSUE THREAD

**Issue by timbatt** [Idlidev/Idlidev-Dino-game-C-#1]
Hey, Idlidev, this is a super neat program! But what libraries did you use and where did you get them?
Such as dos.h, graphics.h, etc... Any library that's not (normally) automatically included with C++.

**Comment by rv178** [comment]
All the libraries I used were included with Turbo C++. dos.h, graphics.h, windows.h etc. are included with Turbo C++ when you install it. 😅 

 And thank you for your lovely comment! :D 

PS. the code would not run in any other compiler other than Turbo C++.

**Comment by timbatt** [comment]
Thanks bro! I was just getting into C++ so I had no idea.

**Comment by rv178** [comment]
Oh, good luck then! :D
